import MaleyLean.Papers.BSD.StatusLedger

open MaleyLean.Papers.BSD

/-!
# BSD endpoint status ledger axiom surface
-/

#print axioms BSDEndpointStatusObligation
#print axioms bsdEndpointStatusObligations
#print axioms bsdEndpointStatusObligations_length_eq
#print axioms bsdEndpointStatusObligationTitlesPopulatedBool_eq_true
#print axioms BSDEndpointStatus
#print axioms BSDEndpointStatusRow
#print axioms bsdEndpointStatusLedger
#print axioms bsdEndpointStatusLedger_obligations_match
#print axioms bsdEndpointStatusLedgerAllSuppliedBool_eq_true
#print axioms bsdEndpointStatusLedgerLeanAnchorsPopulatedBool_eq_true
#print axioms bsdEndpointStatusLedgerSourceEvidencePopulatedBool_eq_true
#print axioms bsdEndpointStatusLedgerClosedCount_eq
#print axioms bsdEndpointStatusLedgerBridgeBoundaryCount_eq
#print axioms bsdEndpointStatusLedgerExternalStandingCount_eq
#print axioms bsdRankEndpointClosurePercent_eq
#print axioms bsdRefinedFormulaBridgeBoundaryPercent_eq
#print axioms bsdReferenceArchiveMaturityPercent_eq
#print axioms bsdEndpointCurrentFormalizationStatusSummaryPopulatedBool_eq_true
#print axioms bsdEndpointCurrentProgressSummaryPopulatedBool_eq_true
#print axioms bsdEndpointFormalizationStatusDocumentPopulatedBool_eq_true
#print axioms bsdEndpointStatusLedgerComplete_holds
