import MaleyLean.Papers.BSD.EndpointClosure

open MaleyLean.Papers.BSD.EndpointClosure

/-!
# BSD endpoint closure axiom surface

The BSD module is currently an audit spine.  These checks make sure the routed
BSD endpoint closeout has no live project axioms.
-/

#print axioms BSDCarrier
#print axioms OfficialBSDRankEndpoint
#print axioms BSDRankMismatch
#print axioms BSDRankBridgeImageSeparatorBranch
#print axioms BSDRankMismatchEndpointOccupation
#print axioms BSDRankEndpointStatus
#print axioms BSDRankEndpointStatusOccupation
#print axioms BSDGovernedEndpointUse
#print axioms BSDNegativeGovernedEndpointUse
#print axioms BSDRankFoundationalCandidate
#print axioms BSDRankEndpointAuditHypotheses
#print axioms bsdRankMismatch_iff_standardNormalForm
#print axioms bsdStandardNormalForm_iff_rankBridgeImageExclusion
#print axioms bsdRankMismatch_iff_bridgeImageExclusion
#print axioms bsdBridgeImageExclusion_iff_separatorBranch
#print axioms bsdRankMismatch_iff_bridgeImageSeparatorBranch
#print axioms bsdRankMismatchOccupation_exhaustion
#print axioms bsdRankMismatchOccupation_nonoptional
#print axioms bsdEndpointResolvingNonGovernance_hiddenFifthCase_impossible
#print axioms bsdGovernedEndpointUse_bivalent
#print axioms bsdNegativeGovernedEndpointUse_has_separatorStatus
#print axioms bsdRankBridgeImageSeparatorBranch_of_negativeGovernedEndpointUse
#print axioms bsdRankBridgeImageSeparatorBranch_theoremLevelDiscriminator
#print axioms bsdOfficialNegativeEndpointUse_endpointStatusGovernance
#print axioms bsdEndpointResolvingMismatchTheorem_is_endpointStatusGovernance
#print axioms bsdRankFoundationalCandidate_classifier_iff
#print axioms bsdNoIndependentRankDiscriminator_of_foundationalNoClassifier
#print axioms BSDRankEndpointAASCContext
#print axioms bsdRankEndpointAuditHypotheses_of_foundationalNoClassifier
#print axioms bsdMismatch_endpointGovernance
#print axioms bsdMismatch_independentRankDiscriminator
#print axioms bsdRankMismatch_impossible
#print axioms bsdRankEquality_forced
#print axioms bsdRankEndpoint_officialCorrespondence
#print axioms officialBSDRankEndpoint_of_auditHypotheses
#print axioms officialBSDRankEndpoint_of_foundationalNoClassifier
#print axioms officialBSDRankEndpoint_of_aascContext
#print axioms bsdRankEndpointAASCContext_closes_rankEndpoint
#print axioms BSDAnalyticContinuationStanding
#print axioms BSDFunctionalEquationStanding
#print axioms BSDLeadingCoefficientStanding
#print axioms BSDRegulatorStanding
#print axioms BSDTamagawaStanding
#print axioms BSDTorsionStanding
#print axioms BSDTateShafarevichStanding
#print axioms BSDFormulaFactorStandingPacket
#print axioms BSDFormulaFactorsStanding
#print axioms bsdFormulaFactorsStanding_of_packet
#print axioms bsdFormulaFactorStandingPacket_components
#print axioms BSDRefinedFormulaConditionalContext
#print axioms BSDRefinedFormulaConditionalContext.formulaFactorsStanding
#print axioms bsdConditionalRefinedFormula_correspondence
#print axioms conditionalRefinedBSDEndpoint_of_context
#print axioms refinedBSDEndpoint_formulaFactorsStanding
#print axioms refinedBSDEndpoint_formula
#print axioms refinedBSDEndpoint_context_iff
#print axioms bsdRefinedFormulaEndpoint_remains_conditional
